{% set name = "validators" %}
{% set version = "0.18.0" %}
{% set sha256 = "bad0cf89a7f2e0aa9c4b76fa5f1d2309125a2c77eb176f03b89a6d5059271e63" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.4.0
    - decorator >=3.4.0

test:
  imports:
    - validators
    - validators.i18n

about:
  home: https://github.com/kvesteri/validators
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Data Validation for Humans

  description: |
    Python data validation for Humans.

    Python has all kinds of data validation tools, but every one of them seems to require defining a schema or form. I wanted to create a simple validation library where validating a simple value does not require defining a form or a schema.
  doc_url: https://validators.readthedocs.io/
  dev_url: https://github.com/kvesteri/validators

extra:
  recipe-maintainers:
    - brl0
