{% set name = "validators" %}
{% set version = "0.35.0" %}
{% set ignore_tests = " --ignore=tests/crypto_addresses/test_eth_address.py" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 992d6c48a4e77c81f1b4daba10d16c3a9bb0dbb79b3a19ea847ff0928e70497a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
  run_constrained:
    # https://github.com/python-validators/validators/blob/0.34.0/pyproject.toml#L51
    - eth-hash >=0.7.0
    - pycryptodome >=3.6.6,<4

# eth-hash is not avaliable in main channel.
test:
  source_files:
    - tests
  imports:
    - validators
    - validators.crypto_addresses
    - validators.i18n
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v {{ ignore_tests }} tests
  requires:
    - pip
    - pytest >=8.3.2

about:
  home: https://github.com/kvesteri/validators
  summary: Python Data Validation for Humans
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  description: |
    Python has all kinds of data validation tools, but every one of them seems to require defining a schema or form.
    I wanted to create a simple validation library where validating a simple value does not require defining a form or a schema.
  dev_url: https://github.com/python-validators/validators
  doc_url: https://yozachar.github.io/pyvalidators/stable/
  description: |
    Python data validation for Humans.

    Python has all kinds of data validation tools, but every one of them seems to require defining a schema or form. I wanted to create a simple validation library where validating a simple value does not require defining a form or a schema.
  doc_url: https://validators.readthedocs.io/
  dev_url: https://github.com/kvesteri/validators

extra:
  recipe-maintainers:
    - brl0
