travis:
  secure:
    BINSTAR_TOKEN: ifqZlSduBsVh/pmi10rOLsHSi43OPltBcx5zF0FX3sjBPQfsBSrZWA2XJ8iPotY+Ryk8bDfN1xBPjY+c3rbg6Zhpj0cfsnV0TmKqcZRCH2Vhhrk93oxML48XoOCPobcibMBy5efu2qpljXTnEwhVnOp3O0gFJ8nXc+zYrJmXdpo5L8Pw+8wenWbGM77AAEoWbxl6KUiu+iE0mFh8cub5/TbWfT+VKvN2hQwPxE5xoJgxIExHI9jysimeKfUigkt9zZywzJU33jAnHcUwkpMQD3N5i9mbn55OZd0JckPYow4xmjO/fN6tHWxp27pzJqRl9CovJIopmNm/t61tU4GA1/bNSSjsYWcmLS3mwPGBmeS6giMoY4/jBNUR72/G/aw3kRhiffJX5akdBEXAkLziQbQqPHSdIyoif+AO348eQmy3TfUXyV8zlQ1e6C83HHy6DjgvBJ34O7pVO3eBfH/4MOBao9vGeUamq8kDL9dldmActeMmjADH6ngOpT8Q/0uhwXK3PBWe1Pu4/0J44rRTUY59jwR1eG7HBWRDvldgdMqnkcdyLzoeY1kqhzlv9iRummIOn+DnQXkX6udL1mu/cfgA5XS4kB1PPTAdh5DlK3zIbVlDRcu1JSqSp5zAr4MvUkqFl95dr4LR2hsj9EOckhXhqkN5Gc/uQ8K9ZpRhVBg=
bot:
  automerge: true
conda_forge_output_validation: true
